title: Chuck Masterson’s Actual Blog
email: WhyWouldIWantYouToBeAbleTo@Email.Me
description: >
    *“What news! how much more important to know what that is which was never old!”* —Thoreau
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.chuckmasterson.com" # the base hostname & protocol for your site, e.g. http://example.com
timezone: America/Chicago

# image URLs. Used in fig.html.
image_dirs:
  local:
    root: "/assets/images"
    large: "/lg/"
    small: "/sm/"
  cloudinary:
    root: "http://res.cloudinary.com/chuckmasterson/image/upload"
    large: "/"
    small: "/c_limit,h_450,w_450/"

imageroot: "http://res.cloudinary.com/chuckmasterson/image/upload"
                                    # local: "/assets/images"
imagelarge: "/"                     # local: "/lg/"
imagesmall: "/c_limit,h_450,w_450/" # local: "/sm/"

github_username: chuckmasterson
repository: chuckmasterson/chuckmasterson.github.io
jquery_version: 3.1.1

author:
  chuck:
    pic: "/assets/images/design/chuck.jpg"
    name: "Chuck"
guest_authors:
  misty:
    pic: "/assets/images/design/misty.jpg"
    name: "Misty"

# Build settings
markdown: kramdown
paginate: 7
paginate_path: /blog/page-:num/

# theme: forest
plugins:
  # - jekyll-feed
  - github-pages
  - jekyll-redirect-from
  - jekyll-seo-tags
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /blog/:year/:month/:day/:title

staticman:
  api: "https://hkstaticchuck.herokuapp.com/v3/entry/github/chuckmasterson/chuckmasterson.github.io/master/comments"
  path: "_data/comments/test-slug"
