title: Chuck Masterson’s Actual Blog
email: WhyWouldIWantYouToBeAbleTo@Email.Me
description: >
    *“What news! how much more important to know what that is which was never old!”* —Thoreau
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chuckmasterson.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# image URLs. Used in fig.html.
imageroot: "http://res.cloudinary.com/chuckmasterson/image/upload"
                                    # local: "/assets/images"
imagelarge: "/"                     # local: "/lg/"
imagesmall: "/c_limit,h_450,w_450/" # local: "/sm/"

github_username: chuckmasterson
repository: chuckmasterson/chuckmasterson.github.io
jquery_version: 3.1.1
author: Chuck

# Build settings
markdown: kramdown
paginate: 7
paginate_path: /blog/page-:num/

# theme: forest
gems:
  - jekyll-feed
  - github-pages
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /blog/:year/:month/:day/:title
